### ISSUE TITLE
Bug/Regression introduced on latest commits

### ISSUE THREAD

**Issue by elbowz** [marvinroger/homie-esp8266#262] opened 2016-12-14 19:03 UTC
If you upload the example ```TemperatureSensor.ino```, you'll get:

```
🔌 Booting into normal mode 🔌
{} Stored configuration
  • Hardware device ID: *******
  • Device ID: *******
  • Boot mode: unknown
  • Name: *******
  • Wi-Fi: 
    ◦ SSID: *******
    ◦ Password not shown
  • MQTT: 
    ◦ Host: *******
    ◦ Port: 1883
    ◦ Base topic: homie/
    ◦ Auth? yes
    ◦ Username: homeclient
    ◦ Password not shown
  • OTA: 
    ◦ Enabled? yes
↕ Attempting to connect to Wi-Fi...
Temperature: 22.00 °C
✖ setNodeProperty(): impossible now
✔ Wi-Fi connected
Triggering WIFI_CONNECTED event...
↕ Attempting to connect to MQTT...
Sending initial information...
✔ MQTT ready
Triggering MQTT_CONNECTED event...
Calling setup function...
〽 Sending statistics...
  • Wi-Fi signal quality: 36%
  • Uptime: 8s
```

you can see the error `✖ setNodeProperty(): impossible now`...

On my personal sketch (more complicated) the wi-fi connection take a lot of time to be established (respect to precedent version). In the meantime `homieLoop` and `homieSetup` functions are executed, but with no connection return error...

Thanks!

edit: after some experiments I think the issue is related to this commit 0527756f3d19120a2b7d2ef0aa21ee8377e99b61

**Comment by marvinroger** [comment] 2017-01-23 22:22
Closing as a duplicate of #260, feel free to reopen if you think this is not the case.

**Closed by marvinroger** 2017-01-23 22:22 UTC
Labels: bug, duplicate
